export const strings = {
  // Common
  next: 'Next',
  login: 'Login',
  register: 'Register',
  email: 'Email',
  password: 'Password',
  home: 'Home',
  reset: 'Reset',
  sending: 'Sending...',
  loggingIn: 'Logging in...',
  settingPassword: 'Setting Password...',
  setPassword: 'Set Password',
  resend: 'Resend',
  verify: 'Verify',
  verifying: 'Verifying',
  
  // SplashScreen
  drive: 'Drive ',
  deliver: 'Deliver.',
  earn: 'Earn',
  grow:'Grow',
  
  // LoginScreen
  loginSubtitle: 'Enter your email and Password to log in.',
  enterYourEmail: 'Enter your email',
  enterYourPassword: 'Enter your password',
  forgotPassword: 'Forgot Password?',
  dontHaveAccount: "Don't have an account? ",
  emailRequired: 'Email is required',
  invalidEmail: 'Invalid email address',
  passwordRequired: 'Password is required',
  countryCode:"Country code is required",
  passwordMinLength: 'Password must be at least 6 characters',
  loginFailed: 'Login failed. Please try again.',
  loginSuccessful: 'Login Successful 🎉',
  
  // RegisterScreen
  registerSubtitle: "Join Raun as a verified driver",
  fullName: 'Full Name',
  firstName: 'First Name',
  surName: 'Surname',
  enterFullName: 'Enter your full name',
  enterFirstName: 'Enter your First name',
  enterSurName: 'Enter your Surname',
  phoneNumber: 'Phone Number',
  enterPhoneNumber: '77 123 4567',
  identityDocument: 'National ID',
  uploadIdentityDocument: 'Upload Identity Document / Passport',
  uploadDocument: 'Upload Document',
  uploadId: 'Upload ID',
  uploadClearSelfie: 'Upload clear face photo',
  uploadClearSelfiePhoto: 'Upload clear selfie photo',
  address: 'Address',
  streetAddress1: 'Street Address 1',
  streetAddress2: 'Street Address 2',
  enterAddress: 'Enter Address',
  country: 'Country',
  selectCountry: 'Select your country',
  city: 'City',
  enterCity: 'Enter city',
  stateProvince: 'State/Province',
  selectState: 'Select your state',
  zipCode: 'Zip Code',
  enterZipCode: 'Enter zip code',
  uploadProofAddress: 'Upload proof of address',
  uploadUtilityBill: 'Upload utility bill / affidavit',
  vehicleInformation: 'Vehicle Information',
  make: 'Make',
  modalYear: 'Model(Year)',
  vehicleTrailer: 'Vehicle Trailer',
  selectTrailerType: 'Select trailer type',
  vehicleColor: 'Vehicle Color',
  vehicleRegistrationNumber: 'Vehicle Registration Number',
  vehicleMeasurements: 'Vehicle Measurments',
  feet: 'Feet',
  meters: 'Meters',
  width: 'Width',
  height: 'Height',
  length: 'Length',
  vehiclePhotos: 'Vehicle Photos',
  front: 'Front',
  side: 'Side',
  back: 'Back',
  documents: 'Documents',
  vehicleRegistration: 'Vehicle Registration',
  insurance: 'Insurance',
  driversLicense: 'Driver\'s License',
  uploadDrivingLicense: 'Upload Driving License',
  registering: 'Registering...',
  alreadyHaveAccount: 'Already have an account?',
  selectCountryCode: 'Select Country Code',
  selectCountryTitle: 'Select Country',
  selectStateTitle: 'Select State',
  selectVehicleTrailer: 'Select Vehicle Trailer',
  close: 'Close',
  // Validation messages
  fullNameRequired: 'Full name is required',
  phoneRequired: 'Phone number is required',
  addressRequired: 'Address is required',
  countryRequired: 'Country is required',
  stateRequired: 'State is required',
  cityRequired: 'City is required',
  zipCodeRequired: 'Zip code is required',
  genderisRequired: 'Gender is required',
  identityDocumentRequired: 'Identity document is required',
  idUploadRequired: 'ID upload is required',
  selfiePhotoRequired: 'Selfie photo is required',
  proofAddressRequired: 'Proof of address is required',
  confirmPasswordRequired: 'Confirm Password is required',
  vehicleMakeRequired: 'Vehicle make is required',
  vehicleYearRequired: 'Vehicle year is required',
  vehicleColorRequired: 'Vehicle color is required',
  vehicleTrailerRequired: 'Vehicle Trailer is required',
  registrationNumberRequired: 'Registration number is required',
  vehicleWidthRequired: 'Vehicle width is required',
  vehicleHeightRequired: 'Vehicle height is required',
  vehicleLengthRequired: 'Vehicle length is required',
  vehicleFrontPhotoRequired: 'Vehicle front photo is required',
  vehicleSidePhotoRequired: 'Vehicle side photo is required',
  vehicleBackPhotoRequired: 'Vehicle back photo is required',
  vehicleRegistrationRequired: 'Vehicle registration document is required',
  insuranceRequired: 'Insurance document is required',
  drivingLicenseRequired: 'Driving license document is required',
  validPhoneNumber: 'Please enter a valid phone number 10 digits',
  validZipCode: 'Please enter a valid zip code (4 or 6 digits)',
  registrationSuccessful: 'Registration Successful',
  
  // ReviewScreen
  profileUnderReview: 'Profile Under Review',
  detailsBeingVerified: 'Your Details Are Being Verified',
  reviewMessage: "We are reviewing your details. This won't take long.\nWe'll notify you once approved.",
  
  // ForgotPasswordScreen
  forgotPasswordTitle: 'Forgot Password',
  forgotPasswordSubtitle: 'Enter your email address to reset password',
  validEmailRequired: 'Please enter a valid email address',
  failedSendOtp: 'Failed to send OTP',
  somethingWentWrong: 'Something went wrong. Please try again.',
  
  // ResetPasswordScreen
  resetPasswordTitle: 'Reset Password',
  resetPasswordSubtitle: 'Create a new password for your account',
  newPassword: 'New Password',
  enterNewPassword: 'Enter new password',
  confirmPassword: 'Confirm Password',
  confirmPasswordPlaceholder: 'Confirm password',
  passwordMin6Chars: 'Password must be at least 6 characters',
  passwordRequirements: 'Password must contain numbers, letters and special characters',
  passwordsNotMatch: 'Passwords do not match',
  failedResetPassword: 'Failed to reset password',
  passwordResetSuccessful: 'Password reset successful 🎉',
  
  // EmailVerifyScreen
  enterYourOtp: 'Enter Your OTP',
  enterOtpSentToEmail: 'Enter OTP sent to your email address',
  didntReceiveOtp: 'Didn\'t receive OTP?',
  resendInSeconds: 'Resend in {0}s',

  emailNotFound: 'Email not found',
  pleaseEnter6DigitOtp: 'Please enter 6 digit OTP',
  otpVerificationFailed: 'OTP verification failed. Please try again.',
  failedToResendOtp: 'Failed to resend OTP',
  otpSentSuccessfully: 'OTP sent successfully',
  
  // Common file size
  kb: 'KB',
   selectImage: 'Select Image',
  chooseOption: 'Choose an option',
  camera: 'Camera',
  gallery: 'Gallery',
  cancel: 'Cancel',
  cropImage:"Crop Image"
};